### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Camilin1904**

### CODE REVIEW

**Comment by AndresCamiloRR** [comment]
Faith

**Review by AndresCamiloRR — APPROVED** [review]
First Sprint 1% ability 99% faith

**Review by SebasL07 — APPROVED** [review]
It seems good to me ;)

**Review by Salazq — APPROVED** [review]
Changes checked and accepted

**Review by BrayanOrteg — APPROVED** [review]
Beautiful work 👌

**Pull request merged**
